apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-service
  namespace: flag-service
  labels:
    app: flag-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flag-service
  template:
    metadata:
      labels:
        app: flag-service
    spec:
      imagePullSecrets:
        - name: ecr-pull-secret
      containers:
        - name: flag-service
          image: 667070726571.dkr.ecr.us-east-1.amazonaws.com/togglemaster-flag:v1.0.0-55949fa
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: flag-service-config
                  key: PORT
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: flag-service-config
                  key: AUTH_SERVICE_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: flag-service-secret
                  key: DATABASE_URL
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "otel-collector.monitoring.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
            - name: OTEL_SERVICE_NAME
              value: "flag-service"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "namespace=flag-service"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 3
