apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-service-secret
  namespace: auth-service
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: auth-service-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: togglemaster/auth/db_url
    - secretKey: MASTER_KEY
      remoteRef:
        key: togglemaster/auth/master_key
