apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: analytics-service
data:
  PORT: "8005"
  AWS_REGION: "us-east-1"
  AWS_DYNAMODB_TABLE: "analytics-events"
  AWS_ENDPOINT_URL: ""
